# Generated by Django 5.2.7 on 2025-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_admincontactmodel_anniversarymodel_gallerymodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admincontactmodel',
            old_name='whatsapp',
            new_name='whatsapp_contact',
        ),
        migrations.AddField(
            model_name='admincontactmodel',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admincontactmodel',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admincontactmodel',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admincontactmodel',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admincontactmodel',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
