# Generated by Django 5.2.7 on 2025-10-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_servicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTripModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Check Box', 'check box'), ('Textarea', 'textarea'), ('Radio Button', 'radio button'), ('Drop Down', 'drop down')], max_length=20)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
    ]
