# Generated by Django 5.2.7 on 2025-10-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_plantripmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantripmodel',
            name='label',
            field=models.CharField(default='fdfd', help_text='Enter the question or label for this field.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantripmodel',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options (only for Drop Down, Radio Button, or Check Box).', null=True),
        ),
        migrations.AlterField(
            model_name='plantripmodel',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Check Box'), ('textarea', 'Textarea'), ('radio', 'Radio Button'), ('dropdown', 'Drop Down')], max_length=20),
        ),
    ]
