# Generated by Django 5.2.7 on 2025-10-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_plantripmodel_label_plantripmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=200)),
                ('budget_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('how_strict_budget', models.CharField(choices=[('Estimate', 'Estimate'), ('Flexible', 'Flexible'), ('Maximum', 'Maximum')], max_length=10)),
                ('Departure_Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('Trip_Duration', models.CharField(choices=[('1 Day', '1 Day'), ('2 Days', '2 Days'), ('3 Days', '3 Days'), ('4 Days', '4 Days'), ('5 Days', '5 Days'), ('6 Days', '6 Days'), ('7 Days', '7 Days'), ('8 Days', '8 Days'), ('9 Days', '9 Days'), ('10 Days', '10 Days'), ('11 Days', '11 Days'), ('12 Days', '12 Days'), ('13 Days', '13 Days'), ('14+ Days', '14+ Days')], max_length=10)),
                ('lodging_preference', models.CharField(choices=[('5 Star', '5 Star'), ('4 Star', '4 Star'), ('3 Star', '3 Star'), ('2 Star', '2 Star'), ('Camping', 'Camping')], max_length=10)),
                ('Destination', models.CharField(max_length=200)),
                ('Destination2', models.CharField(blank=True, max_length=200, null=True)),
                ('Number_of_People', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10+', '10+')], max_length=10)),
                ('Age_Groups', models.CharField(choices=[('5 and below', '5 and below'), ('6-11', '6-11'), ('12-17', '12-17'), ('18-35', '18-35'), ('36-49', '36-49'), ('50-64', '50-64'), ('65+', '65+')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='PlanTripModel',
        ),
    ]
