# Generated by Django 5.2.7 on 2025-10-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_enquirymodel_delete_plantripmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
