# Generated by Django 5.2.7 on 2025-10-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_galleryimagemodel_galleryvideomodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtoursimagesmodel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UpcomingDestinationHighlightsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(max_length=500)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='admin_app.upcomingtoursmodel')),
            ],
        ),
    ]
