# Generated by Django 5.2.7 on 2025-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_upcomingtoursimagesmodel_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryvideomodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='galleryvideomodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
