# Generated by Django 5.2.7 on 2025-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_galleryvideomodel_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirymodel',
            name='Age_Groups',
        ),
        migrations.RemoveField(
            model_name='enquirymodel',
            name='Departure_Month',
        ),
        migrations.RemoveField(
            model_name='enquirymodel',
            name='Number_of_People',
        ),
        migrations.RemoveField(
            model_name='enquirymodel',
            name='Trip_Duration',
        ),
        migrations.RemoveField(
            model_name='enquirymodel',
            name='budget_per_person',
        ),
        migrations.RemoveField(
            model_name='enquirymodel',
            name='how_strict_budget',
        ),
        migrations.RemoveField(
            model_name='enquirymodel',
            name='lodging_preference',
        ),
        migrations.AlterField(
            model_name='galleryvideomodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
