# Generated by Django 5.2.7 on 2025-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_remove_enquirymodel_age_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirymodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='enquirymodel',
            name='location',
        ),
        migrations.AddField(
            model_name='enquirymodel',
            name='travelPlans',
            field=models.TextField(blank=True, null=True),
        ),
    ]
