# Generated by Django 5.2.7 on 2025-10-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_remove_enquirymodel_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anniversarymodel',
            name='logo',
            field=models.ImageField(default='25_years.png', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anniversarymodel',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='enquirymodel',
            name='phone',
            field=models.CharField(default='1234567890', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upcomingtoursimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
