# Generated by Django 5.2.7 on 2026-01-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_anniversarymodel_logo_alter_anniversarymodel_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heromodel',
            name='image',
        ),
        migrations.CreateModel(
            name='HeroImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the image in the carousel')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_app.heromodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
