from django.urls import path
from .views import HeroListCreateView, HeroImageListCreateView, HeroImageManageView, AnniversaryListCreateView, AboutListCreateView, OptionListCreateView, OptionManageView, UpcomingToursListCreateView, UpcomingToursManageView, UpcomingToursImagesListCreateView, UpcomingToursImagesManageView, UpcomingDestinationHighlightsListCreateView, UpcomingDestinationHighlightsManageView, PopularDestinationListCreateView, PopularDestinationManageView, ServiceListUpdateView, ServiceManageView, ReviewsListCreateView, ReviewsManageView, AdminContactListCreateView, LocationListCreateView, GalleryImageListCreateView, GalleryImageManageView, GalleryVideoListCreateView, GalleryVideoManageView, EnquiryView, GetInTouchListCreateView, GetInTouchManageView, terms_and_conditions_view, privacy_policy_view, cancellation_policy_view
urlpatterns = [
    path('hero_section/', HeroListCreateView.as_view(), name='hero-list-create'),
    path('hero_images/', HeroImageListCreateView.as_view(), name='hero-image-list-create'),
    path('hero_images/<int:id>/', HeroImageManageView.as_view(), name='hero-image-manage'),
    path('anniversary_section/', AnniversaryListCreateView.as_view(), name='anniversary-list-create'),
    path('about_section/', AboutListCreateView.as_view(), name='about-list-create'),
    path('option_section/', OptionListCreateView.as_view(), name='option-list-create'),
    path('option_section/<int:id>/', OptionManageView.as_view(), name='option-manage'),
    path('upcoming_tours_section/', UpcomingToursListCreateView.as_view(), name='upcoming-tours-list-create'),
    path('upcoming_tours_section/<int:id>/', UpcomingToursManageView.as_view(), name='upcoming-tours-manage'),
    path('upcoming_tours_images_section/', UpcomingToursImagesListCreateView.as_view(), name='upcoming-tours-images-list-create'),
    path('upcoming_tours_images_section/<int:id>/', UpcomingToursImagesManageView.as_view(), name='upcoming-tours-images-manage'),
    path('upcoming_destination_highlights_section/', UpcomingDestinationHighlightsListCreateView.as_view(), name='upcoming-destination-highlights-list-create'),
    path('upcoming_destination_highlights_section/<int:id>/', UpcomingDestinationHighlightsManageView.as_view(), name='upcoming-destination-highlights-manage'),
    path('popular_destination_section/', PopularDestinationListCreateView.as_view(), name='popular-destination-list-create'),
    path('popular_destination_section/<int:id>/', PopularDestinationManageView.as_view(), name='popular-destination-manage'),
    path('service_section/', ServiceListUpdateView.as_view(), name='service-list-create'),
    path('service_section/<int:id>/', ServiceManageView.as_view(), name='service-manage'), 
    path('reviews_section/', ReviewsListCreateView.as_view(), name='reviews-list-create'),
    path('reviews_section/<int:id>/', ReviewsManageView.as_view(), name='reviews-manage'),
    path('admin_contact_section/', AdminContactListCreateView.as_view(), name='admin-contact-list-create'),
    path('location_section/', LocationListCreateView.as_view(), name='location-list-create'),
    path('gallery_image_section/', GalleryImageListCreateView.as_view(), name='gallery-image-list-create'),
    path('gallery_image_section/<int:id>/', GalleryImageManageView.as_view(), name='gallery-image-manage'),
    path('gallery_video_section/', GalleryVideoListCreateView.as_view(), name='gallery-video-list-create'),
    path('gallery_video_section/<int:id>/', GalleryVideoManageView.as_view(), name='gallery-video-manage'),
    path('enquiries/', EnquiryView.as_view(), name='enquiries'),
    path('get_in_touch/', GetInTouchListCreateView.as_view(), name='get-in-touch'),
    path('get_in_touch/<int:id>/', GetInTouchManageView.as_view(), name='get-in-touch-manage'),
    path('api/terms_and_conditions/', terms_and_conditions_view, name='terms_and_conditions'),
    path('api/privacy_policy/', privacy_policy_view, name='privacy_policy'),
    path('api/cancellation_policy/', cancellation_policy_view, name='cancellation_policy'),
]